DROP TABLE IF EXISTS `eb_platform_store`;
CREATE TABLE `eb_platform_store` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `mer_id` int(11) NOT NULL COMMENT '商户ID',
  `store_code` varchar(64) DEFAULT NULL COMMENT '门店编码',
  `store_name` varchar(255) NOT NULL COMMENT '门店名称',
  `store_type` varchar(32) NOT NULL COMMENT '门店类型：OFFLINE-线下门店，ONLINE-线上店',
  `support_online_shopping` tinyint(1) DEFAULT '0' COMMENT '是否支持线上购物：0-不支持，1-支持',
  `contact_person` varchar(64) NOT NULL COMMENT '联系人姓名',
  `contact_phone` varchar(32) NOT NULL COMMENT '联系电话',
  `contact_email` varchar(128) DEFAULT NULL COMMENT '联系邮箱',
  `province` varchar(64) NOT NULL COMMENT '省份',
  `province_id` bigint DEFAULT NULL COMMENT '省份ID',
  `city` varchar(64) NOT NULL COMMENT '城市',
  `city_id` bigint DEFAULT NULL COMMENT '城市ID',
  `district` varchar(64) NOT NULL COMMENT '区县',
  `district_id` bigint DEFAULT NULL COMMENT '区县ID',
  `street` varchar(128) DEFAULT NULL COMMENT '街道',
  `street_id` bigint DEFAULT NULL COMMENT '街道ID',
  `address_detail` varchar(255) NOT NULL COMMENT '详细地址',
  `full_address` varchar(512) DEFAULT NULL COMMENT '完整地址',
  `latitude` decimal(10,8) DEFAULT NULL COMMENT '纬度',
  `longitude` decimal(11,8) DEFAULT NULL COMMENT '经度',
  `business_hours_start` time DEFAULT NULL COMMENT '营业开始时间',
  `business_hours_end` time DEFAULT NULL COMMENT '营业结束时间',
  `business_days` varchar(32) DEFAULT NULL COMMENT '营业日期：1-7表示周一到周日，逗号分隔',
  `status` tinyint(1) DEFAULT '1' COMMENT '门店状态：0-停用，1-启用',
  `sort` int(11) DEFAULT '0' COMMENT '排序值',
  `description` text COMMENT '门店描述',
  `images` text COMMENT '门店图片，JSON格式存储',
  `tags` varchar(255) DEFAULT NULL COMMENT '门店标签，逗号分隔',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user_id` int(11) DEFAULT NULL COMMENT '创建人ID',
  `update_user_id` int(11) DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  KEY `idx_mer_id` (`mer_id`),
  KEY `idx_store_code` (`store_code`),
  KEY `idx_store_type` (`store_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台门店信息表';